development:
  bucket: meet_dev
  access_key_id: ***********************
  secret_access_key: ***********************
production:
  bucket: meet_pro
  access_key_id: 888888888888888888888888
  secret_access_key: ********************************